// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	DailyNewLimit int32              `json:"daily_new_limit"`
	RetentionGoal float64            `json:"retention_goal"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserReview struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	WordID        pgtype.UUID        `json:"word_id"`
	State         int32              `json:"state"`
	Due           pgtype.Timestamptz `json:"due"`
	Stability     float64            `json:"stability"`
	Difficulty    float64            `json:"difficulty"`
	ElapsedDays   int32              `json:"elapsed_days"`
	ScheduledDays int32              `json:"scheduled_days"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Word struct {
	ID           pgtype.UUID        `json:"id"`
	Korean       string             `json:"korean"`
	English      string             `json:"english"`
	PartOfSpeech pgtype.Text        `json:"part_of_speech"`
	TopikLevel   pgtype.Int4        `json:"topik_level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
