// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNewWordsStartedToday = `-- name: CountNewWordsStartedToday :one
SELECT count(*) FROM user_reviews
WHERE user_id = $1 
AND created_at >= $2
`

type CountNewWordsStartedTodayParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountNewWordsStartedToday(ctx context.Context, arg CountNewWordsStartedTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewWordsStartedToday, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLevelProficiency = `-- name: GetLevelProficiency :many
SELECT 
    topik_level,
    COUNT(*) as total,
    COUNT(r.id) as reviewed
FROM words
LEFT JOIN user_reviews r ON words.id = r.word_id AND r.user_id = $1
GROUP BY topik_level
ORDER BY topik_level
`

type GetLevelProficiencyRow struct {
	TopikLevel pgtype.Int4 `json:"topik_level"`
	Total      int64       `json:"total"`
	Reviewed   int64       `json:"reviewed"`
}

func (q *Queries) GetLevelProficiency(ctx context.Context, userID pgtype.UUID) ([]GetLevelProficiencyRow, error) {
	rows, err := q.db.Query(ctx, getLevelProficiency, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLevelProficiencyRow
	for rows.Next() {
		var i GetLevelProficiencyRow
		if err := rows.Scan(&i.TopikLevel, &i.Total, &i.Reviewed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewWordsForUser = `-- name: GetNewWordsForUser :many
SELECT id, korean, english, part_of_speech, topik_level, created_at FROM words
WHERE id NOT IN (
    SELECT word_id FROM user_reviews WHERE user_id = $1
)
AND (topik_level = $3 OR $3 = 0)
ORDER BY RANDOM()
LIMIT $2
`

type GetNewWordsForUserParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Limit      int32       `json:"limit"`
	TopikLevel pgtype.Int4 `json:"topik_level"`
}

func (q *Queries) GetNewWordsForUser(ctx context.Context, arg GetNewWordsForUserParams) ([]Word, error) {
	rows, err := q.db.Query(ctx, getNewWordsForUser, arg.UserID, arg.Limit, arg.TopikLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Korean,
			&i.English,
			&i.PartOfSpeech,
			&i.TopikLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReview = `-- name: GetReview :one
SELECT id, user_id, word_id, state, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, last_review, created_at, updated_at FROM user_reviews
WHERE user_id = $1 AND word_id = $2
`

type GetReviewParams struct {
	UserID pgtype.UUID `json:"user_id"`
	WordID pgtype.UUID `json:"word_id"`
}

func (q *Queries) GetReview(ctx context.Context, arg GetReviewParams) (UserReview, error) {
	row := q.db.QueryRow(ctx, getReview, arg.UserID, arg.WordID)
	var i UserReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WordID,
		&i.State,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.LastReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeeklyActivity = `-- name: GetWeeklyActivity :many
SELECT date_trunc('day', updated_at)::date as study_date
FROM user_reviews
WHERE user_id = $1 AND updated_at >= $2
GROUP BY study_date
ORDER BY study_date DESC
`

type GetWeeklyActivityParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWeeklyActivity(ctx context.Context, arg GetWeeklyActivityParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, getWeeklyActivity, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var study_date pgtype.Date
		if err := rows.Scan(&study_date); err != nil {
			return nil, err
		}
		items = append(items, study_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueReviews = `-- name: ListDueReviews :many
SELECT w.id, w.korean, w.english, w.part_of_speech, w.topik_level, w.created_at, r.state, r.due, r.stability, r.difficulty, r.elapsed_days, r.scheduled_days, r.reps, r.lapses, r.last_review
FROM words w
JOIN user_reviews r ON w.id = r.word_id
WHERE r.user_id = $1 AND r.due <= $2
AND (w.topik_level = $4 OR $4 = 0)
ORDER BY r.due ASC
LIMIT $3
`

type ListDueReviewsParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Due        pgtype.Timestamptz `json:"due"`
	Limit      int32              `json:"limit"`
	TopikLevel pgtype.Int4        `json:"topik_level"`
}

type ListDueReviewsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Korean        string             `json:"korean"`
	English       string             `json:"english"`
	PartOfSpeech  pgtype.Text        `json:"part_of_speech"`
	TopikLevel    pgtype.Int4        `json:"topik_level"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	State         int32              `json:"state"`
	Due           pgtype.Timestamptz `json:"due"`
	Stability     float64            `json:"stability"`
	Difficulty    float64            `json:"difficulty"`
	ElapsedDays   int32              `json:"elapsed_days"`
	ScheduledDays int32              `json:"scheduled_days"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
}

func (q *Queries) ListDueReviews(ctx context.Context, arg ListDueReviewsParams) ([]ListDueReviewsRow, error) {
	rows, err := q.db.Query(ctx, listDueReviews,
		arg.UserID,
		arg.Due,
		arg.Limit,
		arg.TopikLevel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueReviewsRow
	for rows.Next() {
		var i ListDueReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Korean,
			&i.English,
			&i.PartOfSpeech,
			&i.TopikLevel,
			&i.CreatedAt,
			&i.State,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.LastReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryWords = `-- name: ListLibraryWords :many
SELECT 
    w.id, w.korean, w.english, w.part_of_speech, w.topik_level,
    COALESCE(r.state, -1)::int as state,
    r.due, r.reps
FROM words w
LEFT JOIN user_reviews r ON w.id = r.word_id AND r.user_id = $1
ORDER BY 
    state DESC, 
    w.topik_level ASC, 
    w.korean ASC
LIMIT $2 OFFSET $3
`

type ListLibraryWordsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListLibraryWordsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Korean       string             `json:"korean"`
	English      string             `json:"english"`
	PartOfSpeech pgtype.Text        `json:"part_of_speech"`
	TopikLevel   pgtype.Int4        `json:"topik_level"`
	State        int32              `json:"state"`
	Due          pgtype.Timestamptz `json:"due"`
	Reps         pgtype.Int4        `json:"reps"`
}

func (q *Queries) ListLibraryWords(ctx context.Context, arg ListLibraryWordsParams) ([]ListLibraryWordsRow, error) {
	rows, err := q.db.Query(ctx, listLibraryWords, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibraryWordsRow
	for rows.Next() {
		var i ListLibraryWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Korean,
			&i.English,
			&i.PartOfSpeech,
			&i.TopikLevel,
			&i.State,
			&i.Due,
			&i.Reps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReview = `-- name: UpsertReview :one
INSERT INTO user_reviews (
    user_id, word_id, state, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, last_review, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
ON CONFLICT (user_id, word_id) DO UPDATE SET
    state = EXCLUDED.state,
    due = EXCLUDED.due,
    stability = EXCLUDED.stability,
    difficulty = EXCLUDED.difficulty,
    elapsed_days = EXCLUDED.elapsed_days,
    scheduled_days = EXCLUDED.scheduled_days,
    reps = EXCLUDED.reps,
    lapses = EXCLUDED.lapses,
    last_review = EXCLUDED.last_review,
    updated_at = NOW()
RETURNING id, user_id, word_id, state, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, last_review, created_at, updated_at
`

type UpsertReviewParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	WordID        pgtype.UUID        `json:"word_id"`
	State         int32              `json:"state"`
	Due           pgtype.Timestamptz `json:"due"`
	Stability     float64            `json:"stability"`
	Difficulty    float64            `json:"difficulty"`
	ElapsedDays   int32              `json:"elapsed_days"`
	ScheduledDays int32              `json:"scheduled_days"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
}

func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) (UserReview, error) {
	row := q.db.QueryRow(ctx, upsertReview,
		arg.UserID,
		arg.WordID,
		arg.State,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.ElapsedDays,
		arg.ScheduledDays,
		arg.Reps,
		arg.Lapses,
		arg.LastReview,
	)
	var i UserReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WordID,
		&i.State,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.LastReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
