// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash
) VALUES (
    $1, $2
)
RETURNING id, email, password_hash, daily_new_limit, retention_goal, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DailyNewLimit,
		&i.RetentionGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, daily_new_limit, retention_goal, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DailyNewLimit,
		&i.RetentionGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, daily_new_limit, retention_goal, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DailyNewLimit,
		&i.RetentionGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLimits = `-- name: UpdateUserLimits :one
UPDATE users
SET daily_new_limit = $2,
    retention_goal = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, daily_new_limit, retention_goal, created_at, updated_at
`

type UpdateUserLimitsParams struct {
	ID            pgtype.UUID `json:"id"`
	DailyNewLimit int32       `json:"daily_new_limit"`
	RetentionGoal float64     `json:"retention_goal"`
}

func (q *Queries) UpdateUserLimits(ctx context.Context, arg UpdateUserLimitsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLimits, arg.ID, arg.DailyNewLimit, arg.RetentionGoal)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DailyNewLimit,
		&i.RetentionGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
