// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: words.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWord = `-- name: CreateWord :one
INSERT INTO words (
    korean, english, part_of_speech, topik_level
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (korean, english) DO UPDATE SET
    part_of_speech = COALESCE(NULLIF(EXCLUDED.part_of_speech, ''), words.part_of_speech),
    topik_level = COALESCE(NULLIF(EXCLUDED.topik_level, 0), words.topik_level)
RETURNING id, korean, english, part_of_speech, topik_level, created_at
`

type CreateWordParams struct {
	Korean       string      `json:"korean"`
	English      string      `json:"english"`
	PartOfSpeech pgtype.Text `json:"part_of_speech"`
	TopikLevel   pgtype.Int4 `json:"topik_level"`
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, createWord,
		arg.Korean,
		arg.English,
		arg.PartOfSpeech,
		arg.TopikLevel,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Korean,
		&i.English,
		&i.PartOfSpeech,
		&i.TopikLevel,
		&i.CreatedAt,
	)
	return i, err
}

const getWordByID = `-- name: GetWordByID :one
SELECT id, korean, english, part_of_speech, topik_level, created_at FROM words
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWordByID(ctx context.Context, id pgtype.UUID) (Word, error) {
	row := q.db.QueryRow(ctx, getWordByID, id)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Korean,
		&i.English,
		&i.PartOfSpeech,
		&i.TopikLevel,
		&i.CreatedAt,
	)
	return i, err
}

const listWords = `-- name: ListWords :many
SELECT id, korean, english, part_of_speech, topik_level, created_at FROM words
ORDER BY topik_level, korean
LIMIT $1 OFFSET $2
`

type ListWordsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWords(ctx context.Context, arg ListWordsParams) ([]Word, error) {
	rows, err := q.db.Query(ctx, listWords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Korean,
			&i.English,
			&i.PartOfSpeech,
			&i.TopikLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
